# Generated by Django 3.0.6 on 2020-05-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0005_auto_20200522_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='component',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='component',
            name='text',
        ),
    ]
