# Generated by Django 3.0.6 on 2020-05-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0009_auto_20200522_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='recicleType',
            field=models.IntegerField(null=True),
        ),
    ]
