# Generated by Django 3.0.6 on 2020-05-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0011_auto_20200522_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='components',
            field=models.ManyToManyField(to='cor.Component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='recicleType',
            field=models.IntegerField(choices=[(1, 'Envases'), (2, 'Vidrio'), (3, 'Papel'), (4, 'Organico'), (5, 'Medicamentos'), (6, 'Restos'), (7, 'Punto Limpio'), (8, 'Pilas'), (9, 'Aceite'), (10, 'Ropa')], null=True),
        ),
    ]
