# Generated by Django 3.0.6 on 2020-05-24 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_firebase_auth', '0001_initial'),
        ('cor', '0012_auto_20200522_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fbuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drf_firebase_auth.FirebaseUser'),
        ),
    ]
