# Generated by Django 3.0.6 on 2020-05-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0013_productos_fbuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='nick',
        ),
        migrations.AlterField(
            model_name='productos',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
