# Generated by Django 3.0.6 on 2020-05-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0014_auto_20200524_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='uid',
        ),
        migrations.AlterField(
            model_name='productos',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
