# Generated by Django 3.0.6 on 2020-05-24 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_firebase_auth', '0001_initial'),
        ('cor', '0015_auto_20200524_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBUser',
            fields=[
                ('firebaseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drf_firebase_auth.FirebaseUser')),
            ],
            bases=('drf_firebase_auth.firebaseuser',),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fbuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cor.FBUser'),
        ),
    ]
