# Generated by Django 3.0.6 on 2020-05-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0017_auto_20200524_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='code',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
