# Generated by Django 3.0.6 on 2020-05-24 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_firebase_auth', '0001_initial'),
        ('cor', '0019_auto_20200524_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fbuser',
            field=models.ForeignKey(default=105163069074916034148, on_delete=django.db.models.deletion.DO_NOTHING, to='drf_firebase_auth.FirebaseUserProvider'),
            preserve_default=False,
        ),
    ]
