# Generated by Django 3.0.6 on 2020-05-18 00:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('format', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('url', models.ImageField(upload_to='Products/Images')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('nick', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='Users/Avatars')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
