# Generated by Django 3.0.6 on 2020-05-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0004_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='url',
            new_name='image',
        ),
    ]
