# Generated by Django 3.0.6 on 2020-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0010_component_recicletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='recicleType',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], null=True),
        ),
    ]
