# Generated by Django 3.0.6 on 2020-05-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_firebase_auth', '0001_initial'),
        ('cor', '0020_auto_20200524_0351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='Components',
        ),
        migrations.RenameField(
            model_name='components',
            old_name='recicleType',
            new_name='recycleType',
        ),
        migrations.AlterField(
            model_name='productos',
            name='fbuser',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drf_firebase_auth.FirebaseUser'),
        ),
    ]
