# Generated by Django 3.0.6 on 2020-05-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0021_auto_20200526_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='code',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
